import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import pg from 'pg';

const connectionString = process.env.SCHEDULING_TEST_DATABASE_URL;

async function applyFile(client, relativeUrl) {
  const sql = await readFile(new URL(relativeUrl, import.meta.url), 'utf8');
  await client.query(sql);
}

async function setUpDatabase(client) {
  await client.query('drop schema public cascade; create schema public;');
  await applyFile(client, './fixtures/course-scheduling-stub-schema.sql');
  for (const roleName of ['authenticated', 'anon', 'service_role']) {
    await client.query(`do $$ begin if not exists (select 1 from pg_roles where rolname = '${roleName}') then create role ${roleName}; end if; end $$;`);
  }

  await client.query(`
    create table public.school_calendar (
      id bigint generated by default as identity primary key,
      external_key text not null unique,
      title text not null,
      category text not null default 'holiday',
      start_date date,
      end_date date,
      school_day_end_time time,
      blocks_scheduling boolean not null default false,
      enforce_end_time boolean not null default false,
      is_active boolean not null default true
    )
  `);

  await applyFile(client, '../supabase/migrations/20260802220000_course_scheduling_interface_schema.sql');
  await applyFile(client, '../supabase/migrations/20260802221000_course_scheduling_interface_rpcs.sql');
  await applyFile(client, '../supabase/migrations/20260807120000_course_scheduling_proposed_dates.sql');

  await client.query(`
    create or replace function public.scheduling_apply_course_assignment_revalidation(
      p_activity_id text,
      p_change_reason text default 'test_stub'
    ) returns text language sql as $$ select 'שובץ'::text $$
  `);

  await applyFile(client, '../supabase/migrations/20260807203000_course_scheduling_e2e_alignment.sql');
  await applyFile(client, '../supabase/migrations/20260807223000_course_scheduling_final_consistency.sql');
}

async function authenticate(client) {
  await client.query("select set_config('test.role', 'admin', false)");
  await client.query("select set_config('test.uid', '11111111-1111-1111-1111-111111111111', false)");
}

async function seed(client) {
  await client.query("insert into public.users (auth_user_id, role, is_active, emp_id) values ('11111111-1111-1111-1111-111111111111', 'admin', true, '999')");
  await client.query("insert into public.contacts_instructors (emp_id, full_name, active, address) values (1, 'נועה', 'yes', 'Instructor Home')");
  await client.query("insert into public.instructor_scheduling_profiles (emp_id, gender, instruction_languages, education_levels, course_restriction_mode) values (1, 'female', array['ar'], array['elementary'], 'all')");
  await client.query("insert into public.instructor_availability_rules (emp_id, weekday, available, start_time, end_time) select 1, weekday, true, '08:00', '20:00' from generate_series(0, 5) weekday");
  await client.query("insert into public.contacts_schools (id, school_id, school, authority_id, authority, address) values (1, 100, 'בית ספר א', 10, 'חיפה', 'School Address')");
  await client.query(`insert into public.activities (
    row_id, activity_season, activity_type, status, start_time, end_time, start_date, date_1,
    school, school_id, authority, authority_id, instruction_language, required_instructor_gender,
    education_level, activity_no, activity_name
  ) values (
    'course-a', 'school_2027', 'קורס', 'פתוח', '10:00', '11:00', '2027-09-01', '2027-09-01',
    'בית ספר א', 100, 'חיפה', 10, 'he', 'female', 'elementary', 'A1', 'קורס A'
  )`);
  await client.query(`insert into public.scheduling_travel_cache (
    origin_key, destination_key, distance_km, duration_minutes, calculated_at, expires_at
  ) values (
    public.scheduling_normalize_location('Instructor Home'),
    public.scheduling_normalize_location('School Address'),
    12, 18, now(), now() + interval '30 days'
  )`);
}

test('final consistency migration validates direct activity instructor changes and calendar revalidation', async (t) => {
  if (!connectionString) {
    t.skip('set SCHEDULING_TEST_DATABASE_URL to a disposable Postgres connection string');
    return;
  }

  const client = new pg.Client({ connectionString });
  try {
    await client.connect();
    await setUpDatabase(client);
    await authenticate(client);
    await seed(client);

    await assert.rejects(
      client.query("update public.activities set emp_id=1, instructor_name='נועה' where row_id='course-a'"),
      /scheduling_language_mismatch/
    );

    await client.query("update public.instructor_scheduling_profiles set instruction_languages=array['he'] where emp_id=1");
    await client.query("update public.activities set emp_id=1, instructor_name='נועה' where row_id='course-a'");

    const assigned = await client.query("select emp_id, instructor_name, instructor_assignment_locked, instructor_assignment_status from public.activities where row_id='course-a'");
    assert.equal(Number(assigned.rows[0].emp_id), 1);
    assert.equal(assigned.rows[0].instructor_name, 'נועה');
    assert.equal(assigned.rows[0].instructor_assignment_locked, true);
    assert.equal(assigned.rows[0].instructor_assignment_status, 'שובץ');

    await assert.rejects(
      client.query("update public.activities set instructor_name='שם שגוי' where row_id='course-a'"),
      /instructor_name_mismatch/
    );

    await client.query(`insert into public.school_calendar (
      external_key, title, start_date, end_date, blocks_scheduling, is_active
    ) values ('blocked-2027-09-01', 'חופשה', '2027-09-01', '2027-09-01', true, true)`);

    const blocked = await client.query("select instructor_assignment_status from public.activities where row_id='course-a'");
    assert.equal(blocked.rows[0].instructor_assignment_status, 'נדרש טיפול');

    await client.query("delete from public.school_calendar where external_key='blocked-2027-09-01'");
    const restored = await client.query("select instructor_assignment_status from public.activities where row_id='course-a'");
    assert.equal(restored.rows[0].instructor_assignment_status, 'שובץ');
  } finally {
    await client.end().catch(() => {});
  }
});
