import test from 'node:test';import assert from 'node:assert/strict';import {Worker} from 'node:worker_threads';import {readFile,writeFile} from 'node:fs/promises';import {performance} from 'node:perf_hooks';
import {SchedulingPointWorker} from '../frontend/src/screens/course-scheduling-worker-client.js';
import {buildDynamicCoursePlan,planningWorkspaceCourses} from '../frontend/src/screens/course-scheduling-planning.js';
import {sharedPlanningAffectedCourseIds} from '../frontend/src/screens/course-scheduling-planning-store.js';
import {createRouteClient} from '../frontend/src/screens/course-scheduling-travel.js';
import {decisionInput} from '../scripts/acceptance/scheduling-decision-input.mjs';
const dir=process.env.DECISION_DIR;const endpoint=new URL('../frontend/src/screens/course-scheduling-point.worker.js',import.meta.url).href;
function nativeWorker(crash=false){const entry=`import {parentPort} from 'node:worker_threads';globalThis.self={postMessage:m=>parentPort.postMessage(m)};await import(${JSON.stringify(endpoint)});parentPort.on('message',data=>{if(${crash}&&data.type==='run')throw Error('isolated-worker-crash');self.onmessage({data});});`;const native=new Worker(new URL('data:text/javascript,'+encodeURIComponent(entry)),{type:'module'});const adapter={postMessage:m=>native.postMessage(m),terminate:()=>native.terminate()};native.on('message',data=>adapter.onmessage?.({data}));native.on('error',e=>adapter.onerror?.(e));return adapter;}
test('PR2229 representative source: worker/direct point parity and protected official assignments survive availability delta',async t=>{
 if(!dir)return t.skip('Explicit anonymous isolated fixture required');
 const {input,routes,saved}=await decisionInput(dir);if(process.env.DECISION_CANONICAL==='1'){const plan=JSON.parse(await readFile(dir+'/national-plan.json','utf8'));input.existingRows=plan.rows;input.committedRows=plan.rows;}const target=planningWorkspaceCourses(input.activities).find(a=>!a.instructor_assignment_locked&&input.existingRows.some(r=>r.courseId===a.row_id&&r.instructorEmpId));assert.ok(target,'Real saved proposal required');input.targetCourseIds=[target.row_id];
 const protectedIds=new Set(input.activities.filter(a=>a.instructor_assignment_locked).map(a=>a.row_id));const before=JSON.stringify(input);let routeMisses=0;const invoke=async()=>{routeMisses++;return {data:{calculated:false},error:null};};
 const client=new SchedulingPointWorker({createWorker:nativeWorker,yieldControl:async()=>{}});const timings=[];
 try{
  const start=performance.now();const direct=await buildDynamicCoursePlan({...input,routeClient:createRouteClient({preloadedRows:routes,invoke})});timings.push({name:'direct',ms:performance.now()-start});
  let at=performance.now();const first=await client.run(input,{owner:'isolated-admin',version:'representative-v1',routeRows:routes,routeInvoke:invoke});timings.push({name:'worker-cold',ms:performance.now()-at});assert.deepEqual(first.rows,direct.rows);assert.equal(JSON.stringify(input),before);assert.equal(first.finalPlanValidation.valid,true);
  const native=client.worker;at=performance.now();const warm=await client.run(input,{owner:'isolated-admin',version:'representative-v1',routeRows:routes,routeInvoke:invoke});timings.push({name:'worker-warm',ms:performance.now()-at});assert.equal(client.worker,native);assert.deepEqual(warm.rows,first.rows);
  const selected=first.rows.find(r=>r.courseId===target.row_id);assert.ok(selected.meetings?.length);const blockedDate=selected.meetings[0].date;const sourceMap=new Map(input.activities.map(a=>[a.row_id,a]));const affected=sharedPlanningAffectedCourseIds({shared:{rows:first.rows.map(row=>({activityId:row.courseId,activityUpdatedAt:sourceMap.get(row.courseId)?.updated_at,row,needsRecalc:false}))},activities:input.activities,currentCourseIds:planningWorkspaceCourses(input.activities).map(a=>a.row_id),contextDiff:{changedExceptionInstructorIds:[selected.instructorEmpId]}});
  const changed={...input,existingRows:first.rows,committedRows:first.rows,targetCourseIds:affected,exceptions:{...input.exceptions,[selected.instructorEmpId]:[...(input.exceptions[selected.instructorEmpId]||[]),{exception_date:blockedDate,available:false}]}};
  await writeFile(dir+'/worker-before-block.json',JSON.stringify({targetId:target.row_id,selected,timings,parity:true}));
  at=performance.now();const delta=await client.run(changed,{owner:'isolated-admin',version:'representative-v2',routeRows:routes,routeInvoke:invoke});timings.push({name:'worker-blocked-date-delta',ms:performance.now()-at});assert.equal(delta.finalPlanValidation.valid,true);
  for(const id of protectedIds){const original=first.rows.find(r=>r.courseId===id);if(original){const projection=r=>({instructor:r.instructorEmpId,meetings:r.meetings});assert.deepEqual(projection(delta.rows.find(r=>r.courseId===id)),projection(original),`Protected ${id}`);}}
  await writeFile(dir+'/worker-representative-results.json',JSON.stringify({targetId:target.row_id,blockedDate,protectedRowsChecked:[...protectedIds].filter(id=>input.existingRows.some(r=>r.courseId===id)).length,sourceEngineVersion:process.env.DECISION_CANONICAL==='1'?'v36':'v31',affectedCount:affected.length,timings,routeMisses,metrics:client.metrics,parity:true,protectedUnchanged:true},null,2));
 }catch(error){await writeFile(dir+'/worker-representative-failure.json',JSON.stringify({code:error.code,message:error.message,failures:error.failures,timings,inputUnchanged:JSON.stringify(input)===before},null,2));throw error;}finally{client.dispose();}
});
test('PR2229 representative source: actual worker crash and cancellation keep all saved rows unchanged',async t=>{
 if(!dir)return t.skip('Explicit anonymous isolated fixture required');const {input,routes}=await decisionInput(dir);if(process.env.DECISION_CANONICAL==='1'){const plan=JSON.parse(await readFile(dir+'/national-plan.json','utf8'));input.existingRows=plan.rows;input.committedRows=plan.rows;}input.targetCourseIds=[input.existingRows.find(r=>r.kind==='proposal').courseId];const before=JSON.stringify(input.existingRows),out=[];
 for(const scenario of ['crash','cancel']){const client=new SchedulingPointWorker({createWorker:()=>nativeWorker(scenario==='crash'),yieldControl:async()=>{}}),controller=new AbortController();try{let signaledAt;const run=client.run(input,{owner:'isolated-admin',version:'fault-source-v1',routeRows:routes,routeInvoke:async()=>({data:{calculated:false},error:null}),signal:controller.signal,onProgress:()=>{if(scenario==='cancel'&&!controller.signal.aborted){signaledAt=performance.now();controller.abort();}}});await assert.rejects(run,error=>scenario==='cancel'?error.code==='planning_cancelled':String(error.message).includes('worker'));out.push({scenario,pass:true,cancelMs:signaledAt?performance.now()-signaledAt:null,savedRowsUnchanged:JSON.stringify(input.existingRows)===before});assert.equal(JSON.stringify(input.existingRows),before);}finally{client.dispose();}}
 await writeFile(dir+'/worker-representative-faults.json',JSON.stringify(out,null,2));
});
