import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { PDFDocument, rgb } from "npm:pdf-lib@1.17.1";
import fontkit from "npm:@pdf-lib/fontkit@1.1.1";
import bidiFactory from "npm:bidi-js@1.0.3";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type"};
const clean=(v:unknown)=>String(v??"").trim();
const bidi=bidiFactory();
function rtl(v:unknown){const s=clean(v);const a=s.split("");for(const [l,r] of bidi.getReorderSegments(s,bidi.getEmbeddingLevels(s,"rtl"))){let i=l,j=r;while(i<j){[a[i],a[j]]=[a[j],a[i]];i++;j--;}}return a.join("");}
const money=(v:unknown)=>`${Number(v||0).toLocaleString("he-IL",{minimumFractionDigits:2,maximumFractionDigits:2})} ₪`;
const date=(v:unknown)=>{const m=clean(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}.${m[2]}.${m[1]}`:clean(v)};
const base64=(bytes:Uint8Array)=>{let s="";for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)};
async function token(){const tenant=clean(Deno.env.get("MS_TENANT_ID")),client=clean(Deno.env.get("MS_CLIENT_ID")),secret=clean(Deno.env.get("MS_CLIENT_SECRET"));if(!tenant||!client||!secret)throw new Error("graph_not_configured");const r=await fetch(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:client,client_secret:secret,grant_type:"client_credentials",scope:"https://graph.microsoft.com/.default"})});if(!r.ok)throw new Error("graph_auth_failed");return clean((await r.json()).access_token)}
async function graph(t:string,path:string,options:RequestInit={}){const r=await fetch(`https://graph.microsoft.com/v1.0${path}`,{...options,headers:{Authorization:`Bearer ${t}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});if(!r.ok)throw new Error(`graph_request_failed:${r.status}:${(await r.text()).slice(0,160)}`);return r.status===204?null:r.json()}
async function pdf(account:any){const [regularBytes,boldBytes]=await Promise.all([fetch("https://raw.githubusercontent.com/Taasiyeda2026/dashboard_system/main/frontend/assets/fonts/Arimo-Regular.ttf").then(r=>r.arrayBuffer()),fetch("https://raw.githubusercontent.com/Taasiyeda2026/dashboard_system/main/frontend/assets/fonts/Arimo-Bold.ttf").then(r=>r.arrayBuffer())]);const doc=await PDFDocument.create();doc.registerFontkit(fontkit);const regular=await doc.embedFont(regularBytes,{subset:true}),bold=await doc.embedFont(boldBytes,{subset:true});let page=doc.addPage([595,842]),y=805;const draw=(s:string,x:number,size=10,font=regular)=>page.drawText(rtl(s),{x,y,size,font,color:rgb(.08,.12,.18)});const right=(s:string,size=9,font=regular)=>{draw(s,565-font.widthOfTextAtSize(rtl(s),size),size,font);y-=size+4};right('תעשיידע – תעשייה למען חינוך מתקדם ע"ר',9,bold);right("דניאל פריש 3, תל אביב");right("טלפון: 03-5370368");right("עמותה מס': 580210094");right("אימייל: toni@think.org.il");y-=12;right(`תאריך: ${date(account.issue_date)}`,10);y-=8;right(`חשבון עסקה | ${account.transaction_account_number} | מקור`,17,bold);page.drawLine({start:{x:30,y:y+8},end:{x:565,y:y+8},thickness:1,color:rgb(.1,.35,.55)});y-=12;right(`לכבוד: ${account.customer_name_snapshot}`,11,bold);right(`מספר לקוח: ${account.institution_symbol}`,10);y-=5;right('תוכניות חינוכיות – שנת תשפ"ז',13,bold);y-=8;
for(const line of account.finance_transaction_account_lines||[]){if(y<180){page=doc.addPage([595,842]);y=805;}right(`${line.activity_name_snapshot} | מס׳ גפ״ן ${line.gefen_number_snapshot||"—"} | ${line.billed_hours} שעות | ${money(line.hourly_rate_snapshot)} | ${money(line.amount)}`,10,bold);right("פירוט ביצוע לחיוב",9,bold);right("תאריך | שעות",8,bold);for(const m of line.finance_transaction_account_meetings||[])right(`${date(m.meeting_date)} | 1.5`,8);y-=6;}right(`סה"כ לתשלום | ${money(account.total_amount)}`,13,bold);return new Uint8Array(await doc.save())}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const auth=req.headers.get("authorization")||"";const url=clean(Deno.env.get("SUPABASE_URL")),anon=clean(Deno.env.get("SUPABASE_ANON_KEY")),service=clean(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"));const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:allowed,error:allowError}=await userClient.rpc("app_can_access_finance");if(allowError||!allowed)throw new Error("not_authorized");const body=await req.json(),accountId=clean(body.accountId),driveId=clean(body.driveId),folderId=clean(body.folderItemId);if(!accountId||!driveId||!folderId)throw new Error("account_and_sharepoint_folder_required");const admin=createClient(url,service);const {data:account,error}=await admin.from("finance_transaction_accounts").select("*,finance_transaction_account_lines(*,finance_transaction_account_meetings(*))").eq("id",accountId).single();if(error)throw error;if(!["generating","issued","mail_draft_ready"].includes(account.document_status))throw new Error("account_not_dispatchable");let bytes:Uint8Array,item:any,filename=account.generated_filename;if(account.document_status==="generating"){bytes=await pdf(account);filename=`חשבון עסקה ${account.transaction_account_number} - ${clean(account.customer_name_snapshot).replace(/[\\/:*?\"<>|]/g," ")} - ${date(account.issue_date)}.pdf`;const t=await token();const r=await fetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(folderId)}:/${encodeURIComponent(filename)}:/content?@microsoft.graph.conflictBehavior=fail`,{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/pdf"},body:bytes});if(!r.ok)throw new Error(`sharepoint_upload_failed:${r.status}`);item=await r.json();const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");const {data:final,error:finalError}=await userClient.rpc("finalize_finance_transaction_account",{p_account_id:accountId,p_filename:filename,p_pdf_sha256:hash,p_drive_id:driveId,p_folder_item_id:folderId,p_item_id:item.id,p_web_url:item.webUrl});if(finalError)throw finalError;Object.assign(account,final)}else bytes=await pdf(account);
const recipient=clean(account.customer_email_snapshot);if(!recipient){await userClient.rpc("mark_finance_transaction_outlook",{p_account_id:accountId,p_status:"missing_recipient"});return new Response(JSON.stringify({accountId,filename,outlookStatus:"missing_recipient"}),{headers:{...cors,"Content-Type":"application/json"}})}try{const t=await token(),sender=clean(Deno.env.get("MS_MAIL_SENDER"));if(!sender)throw new Error("mail_sender_not_configured");const draft=await graph(t,`/users/${encodeURIComponent(sender)}/messages`,{method:"POST",body:JSON.stringify({subject:`חשבון עסקה ${account.transaction_account_number} – תעשיידע – ${account.customer_name_snapshot}`,body:{contentType:"Text",content:`שלום,\n\nמצורף חשבון עסקה מס׳ ${account.transaction_account_number} עבור הפעילויות שבוצעו בתקופה הרלוונטית.\n\nנשמח להסדרת התשלום בהתאם לתנאי התשלום המפורטים בחשבון.`},toRecipients:[{emailAddress:{address:recipient}}],attachments:[{"@odata.type":"#microsoft.graph.fileAttachment",name:filename,contentType:"application/pdf",contentBytes:base64(bytes)}]})});await userClient.rpc("mark_finance_transaction_outlook",{p_account_id:accountId,p_status:"draft_ready",p_message_id:draft.id});return new Response(JSON.stringify({accountId,filename,outlookStatus:"draft_ready"}),{headers:{...cors,"Content-Type":"application/json"}})}catch(e){await userClient.rpc("mark_finance_transaction_outlook",{p_account_id:accountId,p_status:"failed",p_error:clean((e as Error).message)});return new Response(JSON.stringify({accountId,filename,outlookStatus:"failed",warning:"החשבון הופק ונשמר, אך יצירת טיוטת המייל נכשלה."}),{headers:{...cors,"Content-Type":"application/json"}})}}catch(e){return new Response(JSON.stringify({error:clean((e as Error).message)}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}});
