-- Import activities_system_ready.csv into public.activities without changing values.
-- Usage from repo root after applying migrations:
--   psql "$SUPABASE_DB_URL" -v csv_path="/absolute/path/activities_system_ready.csv" -f supabase/import/import_activities_system_ready.sql
-- The CSV header must match the listed columns exactly.

\set ON_ERROR_STOP on

create temp table activities_import_stage (
  row_id text,
  activity_family text,
  activity_manager text,
  authority text,
  school text,
  grade text,
  class_group text,
  activity_type text,
  activity_no text,
  activity_name text,
  sessions text,
  price text,
  funding text,
  start_time text,
  end_time text,
  emp_id text,
  instructor_name text,
  emp_id_2 text,
  instructor_name_2 text,
  start_date text,
  end_date text,
  date_1 text,
  date_2 text,
  date_3 text,
  date_4 text,
  date_5 text,
  date_6 text,
  date_7 text,
  date_8 text,
  date_9 text,
  date_10 text,
  date_11 text,
  date_12 text,
  date_13 text,
  date_14 text,
  date_15 text,
  date_16 text,
  date_17 text,
  date_18 text,
  date_19 text,
  date_20 text,
  date_21 text,
  date_22 text,
  date_23 text,
  date_24 text,
  date_25 text,
  date_26 text,
  date_27 text,
  date_28 text,
  date_29 text,
  date_30 text,
  date_31 text,
  date_32 text,
  date_33 text,
  date_34 text,
  date_35 text,
  status text,
  notes text,
  finance_status text,
  finance_notes text,
  operations_private_notes text
);

\copy activities_import_stage from :'csv_path' with (format csv, header true, encoding 'UTF8')

insert into public.activities (
  row_id, activity_family, activity_manager, authority, school, grade, class_group,
  activity_type, activity_no, activity_name, sessions, price, funding, start_time,
  end_time, emp_id, instructor_name, emp_id_2, instructor_name_2, start_date,
  end_date, date_1, date_2, date_3, date_4, date_5, date_6, date_7, date_8,
  date_9, date_10, date_11, date_12, date_13, date_14, date_15, date_16,
  date_17, date_18, date_19, date_20, date_21, date_22, date_23, date_24,
  date_25, date_26, date_27, date_28, date_29, date_30, date_31, date_32,
  date_33, date_34, date_35, status, notes, finance_status, finance_notes,
  operations_private_notes
)
select * from activities_import_stage
on conflict (row_id) do update set
  activity_family = excluded.activity_family,
  activity_manager = excluded.activity_manager,
  authority = excluded.authority,
  school = excluded.school,
  grade = excluded.grade,
  class_group = excluded.class_group,
  activity_type = excluded.activity_type,
  activity_no = excluded.activity_no,
  activity_name = excluded.activity_name,
  sessions = excluded.sessions,
  price = excluded.price,
  funding = excluded.funding,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  emp_id = excluded.emp_id,
  instructor_name = excluded.instructor_name,
  emp_id_2 = excluded.emp_id_2,
  instructor_name_2 = excluded.instructor_name_2,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  date_1 = excluded.date_1,
  date_2 = excluded.date_2,
  date_3 = excluded.date_3,
  date_4 = excluded.date_4,
  date_5 = excluded.date_5,
  date_6 = excluded.date_6,
  date_7 = excluded.date_7,
  date_8 = excluded.date_8,
  date_9 = excluded.date_9,
  date_10 = excluded.date_10,
  date_11 = excluded.date_11,
  date_12 = excluded.date_12,
  date_13 = excluded.date_13,
  date_14 = excluded.date_14,
  date_15 = excluded.date_15,
  date_16 = excluded.date_16,
  date_17 = excluded.date_17,
  date_18 = excluded.date_18,
  date_19 = excluded.date_19,
  date_20 = excluded.date_20,
  date_21 = excluded.date_21,
  date_22 = excluded.date_22,
  date_23 = excluded.date_23,
  date_24 = excluded.date_24,
  date_25 = excluded.date_25,
  date_26 = excluded.date_26,
  date_27 = excluded.date_27,
  date_28 = excluded.date_28,
  date_29 = excluded.date_29,
  date_30 = excluded.date_30,
  date_31 = excluded.date_31,
  date_32 = excluded.date_32,
  date_33 = excluded.date_33,
  date_34 = excluded.date_34,
  date_35 = excluded.date_35,
  status = excluded.status,
  notes = excluded.notes,
  finance_status = excluded.finance_status,
  finance_notes = excluded.finance_notes,
  operations_private_notes = excluded.operations_private_notes;
