const COURSE_OPTIONS = [
  { key: 'biomimicry', label: 'ביומימיקרי' },
  { key: 'rokchim-olam', label: 'רוקחים עולם' },
  { key: 'ai', label: 'בינה מלאכותית' },
  { key: 'premium', label: 'פרימיום' }
];

const INVITATION_TYPES = [
  { key: 'lecture', label: 'הרצאה' },
  { key: 'tour', label: 'סיור' },
  { key: 'graduation', label: 'מפגש סיום קורס' }
];
const SCHOOL_YEAR_OPTIONS = ['תשפ״ו', 'תשפ״ז'];
const BACKGROUNDS = [1, 2, 3, 4, 5].map((i) => ({ key: `background-${i}`, src: `/assets/invitations/backgrounds/background-${i}.png` }));
const FIXED_LOGOS = {
  education: { key: 'education', label: 'משרד החינוך', src: '/assets/invitations/logos/education-logo.png' },
  taasiyeda: { key: 'taasiyeda', label: 'תעשיידע', src: '/assets/invitations/logos/taasiyeda-logo.png' }
};
const FIELD_LABELS = {
  lecture: { text1: 'תיאור ההרצאה', text2: 'מה ילמדו המשתתפים', contact: 'שם המרצה / אורח', contactRole: 'תפקיד / ארגון' },
  tour: { text1: 'תיאור הסיור', text2: 'מה ייחשפו אליו המשתתפים', contact: 'חברה מארחת', contactRole: 'כתובת / מיקום' },
  graduation: { text1: 'תיאור התהליך', text2: 'מה יוצג במפגש', contact: 'מחנכת הכיתה', contactRole: 'משתתפים מטעם תעשיידע' }
};

const formatDateIL = (dateValue) => {
  if (!dateValue) return '______';
  const d = new Date(`${dateValue}T00:00:00`);
  if (Number.isNaN(d.getTime())) return '______';
  return new Intl.DateTimeFormat('he-IL', { day: '2-digit', month: '2-digit', year: '2-digit' }).format(d).replace(/\//g, '.');
};

function ensureInvitationStyles() { /* styles omitted for brevity */
  if (document.getElementById('invitations-screen-style')) return;
  const style = document.createElement('style'); style.id = 'invitations-screen-style';
  style.textContent = `.inv-shell{display:grid;grid-template-columns:minmax(450px,520px) 1fr;gap:24px;direction:rtl}.inv-panel{background:#fff;border:1px solid #dbe5ef;border-radius:18px;padding:16px;max-height:calc(100vh - 40px);overflow:auto}.inv-section-title{font-weight:800;margin:8px 0}.inv-compact-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.inv-field{display:grid;gap:4px}.inv-field input,.inv-field textarea,.inv-field select{border:1px solid #cbd5e1;border-radius:10px;padding:8px;font:inherit}.inv-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.inv-chip{border:1px solid #dbe5e1;background:#f8fafc;border-radius:10px;padding:9px;cursor:pointer}.inv-chip.active{background:#dcfce7}.invitation-preview-viewport{overflow:auto}.invitation-preview-wrapper{display:flex;justify-content:center}.invitation-preview-scale{width:794px;height:1123px;transform:scale(var(--a4-scale,.7));transform-origin:top center}.invitation-print-page{width:794px;min-height:1123px;padding:90px 70px;background-size:cover}.event-row{display:flex;gap:10px;justify-content:center;align-items:center}.event-chip{display:flex;align-items:center;gap:6px}.event-icon{width:14px;height:14px;border-radius:50%}.day{background:#14b8a6}.date{background:#3b82f6}.time{background:#8b5cf6}.location{background:#22c55e}.logo-row{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.logo-slot img{height:40px;object-fit:contain}.inv-print-modal{position:fixed;inset:0;background:rgba(15,23,42,.56);display:flex;align-items:center;justify-content:center;z-index:9999}.inv-print-dialog{background:#fff;padding:16px;border-radius:14px;max-height:92vh;overflow:auto;width:min(980px,95vw)}.inv-btn{border:0;border-radius:10px;padding:10px 12px;background:#0ea5a8;color:#fff;cursor:pointer}.inv-btn.secondary{background:#334155}.inv-empty{padding:44px;text-align:center}.bg-thumbs{display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.bg-thumb{width:100%;height:54px;border:2px solid transparent;border-radius:8px;overflow:hidden;cursor:pointer}.bg-thumb.active{border-color:#0ea5a8}.bg-thumb img{width:100%;height:100%;object-fit:cover}@media (max-width:1200px){.inv-shell{grid-template-columns:1fr}}@media print{@page{size:A4;margin:0}body.printing-invitation *{visibility:hidden!important}body.printing-invitation #print-root,body.printing-invitation #print-root *{visibility:visible!important}#print-root{position:fixed;inset:0;background:white}#print-root .invitation-print-page{width:210mm!important;height:297mm!important;min-height:297mm!important;transform:none!important;scale:none!important;box-shadow:none!important}}`;
  document.head.appendChild(style);
}

const invitationEmptyStateHtml = () => '<div class="inv-empty">כדי להתחיל ליצור הזמנה, בחרו קורס וסוג הזמנה מהחלונית בצד.</div>';

function invitationPreviewHtml(s) {
  const labels = FIELD_LABELS[s.type] || FIELD_LABELS.graduation;
  const logos = s.logoOrder.filter((l) => l.visible && l.src);
  return `<div class="invitation-preview-wrapper"><div class="invitation-preview-scale"><div class="invitation-print-page" style="background-image:url('${s.backgroundSrc}')"><div class="logo-row">${logos.map((l) => `<div class="logo-slot"><img src="${l.src}" alt="${l.label}"/></div>`).join('')}</div><h1>${s.title || 'הזמנה לאירוע'}</h1><h3>${s.schoolYear}</h3><p>תלמידי כיתה ${s.className || '______'} | בית ספר ${s.school || '______'}</p><div><p>${s.text1 || ''}</p><p>${s.text2 || ''}</p></div><div class="event-row"><span class="event-chip"><span class="event-icon day"></span>יום: ${s.day || '______'}</span><span class="event-chip"><span class="event-icon date"></span>תאריך: ${formatDateIL(s.date)}</span><span class="event-chip"><span class="event-icon time"></span>שעה: ${s.time || '______'}</span></div><div class="event-row"><span class="event-chip"><span class="event-icon location"></span>מיקום: ${s.location || '______'}</span></div><p>${labels.contact}: ${s.contact || '______'} | ${labels.contactRole}: ${s.contactRole || '______'}</p><p>משתתפים / נציגים: ${s.participants || '______'}</p></div></div></div>`;
}

export const invitationsScreen = { load: async () => ({}), render() { ensureInvitationStyles(); return `<section class="inv-shell" data-invitations-root><aside class="inv-panel"><h2>מחולל הזמנות</h2><div class="inv-section-title">בחירת קורס</div><div class="inv-grid">${COURSE_OPTIONS.map((c) => `<button class="inv-chip" data-course="${c.key}">${c.label}</button>`).join('')}</div><div class="inv-section-title">בחירת סוג הזמנה</div><div class="inv-grid">${INVITATION_TYPES.map((t) => `<button class="inv-chip" data-type="${t.key}">${t.label}</button>`).join('')}</div><div class="inv-section-title">פרטים כלליים</div><div class="inv-compact-grid"><label class="inv-field"><span>שנת לימודים</span><select data-field="schoolYear">${SCHOOL_YEAR_OPTIONS.map((y) => `<option value="${y}">${y}</option>`).join('')}</select></label><label class="inv-field"><span>כיתה / קהל יעד</span><input data-field="className" /></label><label class="inv-field"><span>בית ספר</span><input data-field="school" /></label></div><div class="inv-section-title">פרטי מועד</div><div class="inv-compact-grid"><label class="inv-field"><span>יום</span><input data-field="day"/></label><label class="inv-field"><span>תאריך</span><input type="date" data-field="date"/></label><label class="inv-field"><span>שעה</span><input type="time" data-field="time"/></label><label class="inv-field"><span>מיקום</span><input data-field="location"/></label></div><div class="inv-section-title">פרטי תוכן</div><label class="inv-field"><span>כותרת אירוע</span><input data-field="title"/></label><label class="inv-field"><span data-text1-label>תיאור</span><textarea data-field="text1"></textarea></label><label class="inv-field"><span data-text2-label>פירוט נוסף</span><textarea data-field="text2"></textarea></label><div class="inv-section-title">משתתפים</div><div class="inv-compact-grid"><label class="inv-field"><span data-contact-label>איש קשר</span><input data-field="contact"/></label><label class="inv-field"><span data-contact-role-label>תפקיד / ארגון</span><input data-field="contactRole"/></label></div><label class="inv-field"><span>משתתפים / נציגים</span><textarea data-field="participants"></textarea></label><div class="inv-section-title">עיצוב</div><div class="bg-thumbs">${BACKGROUNDS.map((b, idx) => `<button type="button" class="bg-thumb ${idx === 0 ? 'active' : ''}" data-background="${b.src}"><img src="${b.src}" alt="${b.key}"/></button>`).join('')}</div><div data-logo-list></div><button type="button" class="inv-btn secondary" data-add-logo>הוספת לוגו</button><div class="inv-section-title">הפקה</div><button type="button" class="inv-btn" data-print>הפק / שמור כ-PDF</button></aside><main class="invitation-preview-viewport" data-inv-preview>${invitationEmptyStateHtml()}</main></section>`; },
  bind({ root }) { const host = root?.querySelector('[data-invitations-root]'); if (!host) return; const state = { course: '', type: '', school: '', className: '', title: '', schoolYear: 'תשפ״ו', day: '', date: '', time: '', location: '', text1: '', text2: '', participants: '', contact: '', contactRole: '', backgroundSrc: BACKGROUNDS[0].src, logoOrder: [{ ...FIXED_LOGOS.education, visible: true, fixed: true }, { ...FIXED_LOGOS.taasiyeda, visible: true, fixed: true }] };
    const renderLogoManager = () => { const wrap = host.querySelector('[data-logo-list]'); if (!wrap) return; wrap.innerHTML = state.logoOrder.map((l, i) => `<div class="inv-field"><span>${l.label}</span><div style="display:flex;gap:6px;align-items:center"><button data-logo-up="${i}">↑</button><button data-logo-down="${i}">↓</button><label><input type="checkbox" data-logo-visible="${i}" ${l.visible ? 'checked' : ''}/>הצג</label>${l.fixed ? '' : '<button data-logo-remove="'+i+'">הסר</button>'}</div></div>`).join(''); };
    const repaint = () => { host.querySelectorAll('[data-course]').forEach((el) => el.classList.toggle('active', el.dataset.course === state.course)); host.querySelectorAll('[data-type]').forEach((el) => el.classList.toggle('active', el.dataset.type === state.type)); const labels = FIELD_LABELS[state.type] || FIELD_LABELS.graduation; host.querySelector('[data-text1-label]').textContent = labels.text1; host.querySelector('[data-text2-label]').textContent = labels.text2; host.querySelector('[data-contact-label]').textContent = labels.contact; host.querySelector('[data-contact-role-label]').textContent = labels.contactRole; renderLogoManager(); const p = host.querySelector('[data-inv-preview]'); const canPreview = Boolean(state.course && state.type); if (p) p.innerHTML = canPreview ? invitationPreviewHtml(state) : invitationEmptyStateHtml(); const wrap = p?.querySelector('.invitation-preview-scale'); if (wrap) { const scale = Math.max(0.68, Math.min(1, ((p.clientWidth || 980) - 20) / 794, ((p.clientHeight || 1200) - 20) / 1123)); wrap.style.setProperty('--a4-scale', String(scale)); } };
    host.addEventListener('click', (e) => { const c = e.target.closest('[data-course]'); if (c) state.course = c.dataset.course; const t = e.target.closest('[data-type]'); if (t) state.type = t.dataset.type; const bg = e.target.closest('[data-background]'); if (bg) { state.backgroundSrc = bg.dataset.background; host.querySelectorAll('.bg-thumb').forEach((b) => b.classList.toggle('active', b === bg)); } const up = e.target.closest('[data-logo-up]'); if (up) { const i = Number(up.dataset.logoUp); if (i > 0) [state.logoOrder[i - 1], state.logoOrder[i]] = [state.logoOrder[i], state.logoOrder[i - 1]]; } const down = e.target.closest('[data-logo-down]'); if (down) { const i = Number(down.dataset.logoDown); if (i < state.logoOrder.length - 1) [state.logoOrder[i + 1], state.logoOrder[i]] = [state.logoOrder[i], state.logoOrder[i + 1]]; } const rm = e.target.closest('[data-logo-remove]'); if (rm) state.logoOrder.splice(Number(rm.dataset.logoRemove), 1); if (c || t || bg || up || down || rm) repaint(); });
    host.addEventListener('input', (e) => { const field = e.target?.dataset?.field; if (field) state[field] = e.target.value || ''; const visible = e.target?.dataset?.logoVisible; if (visible !== undefined) state.logoOrder[Number(visible)].visible = Boolean(e.target.checked); repaint(); });
    host.querySelector('[data-add-logo]')?.addEventListener('click', () => { const input = document.createElement('input'); input.type = 'file'; input.accept = 'image/*'; input.onchange = () => { const file = input.files?.[0]; if (!file) return; const r = new FileReader(); r.onload = () => { state.logoOrder.push({ key: `extra-${Date.now()}`, label: prompt('שם לוגו קצר', 'לוגו נוסף') || 'לוגו נוסף', src: String(r.result || ''), visible: true }); repaint(); }; r.readAsDataURL(file); }; input.click(); });
    const ensurePrintRoot = () => { let r = document.getElementById('print-root'); if (!r) { r = document.createElement('div'); r.id = 'print-root'; document.body.appendChild(r); } return r; };
    const cleanup = () => { const r = document.getElementById('print-root'); if (r) r.innerHTML = ''; document.body.classList.remove('printing-invitation'); };
    host.querySelector('[data-print]')?.addEventListener('click', () => { if (!state.course || !state.type) return; let modal = document.getElementById('inv-print-modal'); if (!modal) { modal = document.createElement('div'); modal.id = 'inv-print-modal'; modal.className = 'inv-print-modal'; modal.innerHTML = '<div class="inv-print-dialog"><h3>תצוגה מוקדמת להזמנה</h3><p>בדקו שהפרטים, הלוגואים והרקע מוצגים כראוי. לאחר מכן לחצו על “הדפס / שמור כ-PDF”.</p><div data-modal-preview></div><button class="inv-btn" data-modal-do-print>הדפס / שמור כ-PDF</button><button class="inv-btn secondary" data-modal-close>ביטול</button></div>'; document.body.appendChild(modal); modal.addEventListener('click', (ev) => { if (ev.target === modal || ev.target.closest('[data-modal-close]')) modal.remove(); }); modal.querySelector('[data-modal-do-print]')?.addEventListener('click', () => { const src = modal.querySelector('.invitation-print-page'); if (!src) return; const pr = ensurePrintRoot(); pr.innerHTML = ''; pr.appendChild(src.cloneNode(true)); document.body.classList.add('printing-invitation'); window.print(); }); }
      modal.querySelector('[data-modal-preview]').innerHTML = host.querySelector('[data-inv-preview]').innerHTML;
    });
    window.addEventListener('afterprint', cleanup); window.addEventListener('resize', repaint); repaint(); }
};
