create table if not exists public.contact_emails (
  id bigint generated by default as identity primary key,
  contact_id bigint not null references public.contacts_schools(id) on delete cascade,
  email text not null,
  is_primary boolean not null default false,
  source text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists contact_emails_contact_email_key
  on public.contact_emails (contact_id, lower(btrim(email)));
create unique index if not exists contact_emails_one_active_primary_key
  on public.contact_emails (contact_id)
  where is_primary and active;
create index if not exists idx_contact_emails_contact_id
  on public.contact_emails (contact_id);
create index if not exists idx_contact_emails_email_lower
  on public.contact_emails (lower(btrim(email)));

alter table public.contact_emails enable row level security;

drop policy if exists allow_dashboard_select on public.contact_emails;
create policy allow_dashboard_select
  on public.contact_emails for select to anon, authenticated using (true);

drop policy if exists contact_emails_insert_managers_dashboard on public.contact_emails;
create policy contact_emails_insert_managers_dashboard
  on public.contact_emails for insert to authenticated
  with check (
    public.app_current_role() = any (array[
      'admin','operation_manager','activities_manager','domain_manager',
      'instructor_manager','business_development_manager'
    ]::text[])
    or exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
        and u.is_active = true
        and u.manage_proposals_agreements = true
    )
  );

drop policy if exists contact_emails_update_managers_dashboard on public.contact_emails;
create policy contact_emails_update_managers_dashboard
  on public.contact_emails for update to authenticated
  using (
    public.app_current_role() = any (array[
      'admin','operation_manager','activities_manager','domain_manager',
      'instructor_manager','business_development_manager'
    ]::text[])
    or exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
        and u.is_active = true
        and u.manage_proposals_agreements = true
    )
  )
  with check (
    public.app_current_role() = any (array[
      'admin','operation_manager','activities_manager','domain_manager',
      'instructor_manager','business_development_manager'
    ]::text[])
    or exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
        and u.is_active = true
        and u.manage_proposals_agreements = true
    )
  );

drop policy if exists contact_emails_delete_managers_dashboard on public.contact_emails;
create policy contact_emails_delete_managers_dashboard
  on public.contact_emails for delete to authenticated
  using (
    public.app_current_role() = any (array[
      'admin','operation_manager','activities_manager','domain_manager',
      'instructor_manager','business_development_manager'
    ]::text[])
    or exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
        and u.is_active = true
        and u.manage_proposals_agreements = true
    )
  );

create or replace function public.normalize_contact_email(p_email text)
returns text language sql immutable parallel safe
as $$
  select lower(regexp_replace(btrim(coalesce(p_email, '')), '\s+', '', 'g'));
$$;

create or replace function public.contact_email_before_write()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_has_primary boolean;
begin
  new.email := public.normalize_contact_email(new.email);
  if new.email = '' then raise exception 'contact email cannot be empty'; end if;
  new.updated_at := now();

  if pg_trigger_depth() > 1 then return new; end if;

  if new.is_primary then
    update public.contact_emails
    set is_primary = false, updated_at = now()
    where contact_id = new.contact_id
      and id is distinct from new.id
      and is_primary
      and public.normalize_contact_email(email) <> new.email;
  else
    select exists (
      select 1 from public.contact_emails ce
      where ce.contact_id = new.contact_id
        and ce.active and ce.is_primary
        and ce.id is distinct from new.id
    ) into v_has_primary;
    if not v_has_primary then new.is_primary := true; end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_contact_email_before_write on public.contact_emails;
create trigger trg_contact_email_before_write
before insert or update on public.contact_emails
for each row execute function public.contact_email_before_write();

create or replace function public.sync_contact_primary_email_from_contact_emails()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_contact_id bigint;
  v_primary_email text;
begin
  v_contact_id := case when tg_op = 'DELETE' then old.contact_id else new.contact_id end;

  if not exists (
    select 1 from public.contact_emails ce
    where ce.contact_id = v_contact_id and ce.active and ce.is_primary
  ) then
    update public.contact_emails
    set is_primary = true, updated_at = now()
    where id = (
      select ce.id from public.contact_emails ce
      where ce.contact_id = v_contact_id and ce.active
      order by ce.created_at, ce.id limit 1
    );
  end if;

  select ce.email into v_primary_email
  from public.contact_emails ce
  where ce.contact_id = v_contact_id and ce.active and ce.is_primary
  order by ce.id limit 1;

  update public.contacts_schools cs
  set email = nullif(v_primary_email, '')
  where cs.id = v_contact_id
    and public.normalize_contact_email(cs.email)
        is distinct from public.normalize_contact_email(v_primary_email);
  return null;
end;
$$;

drop trigger if exists trg_sync_contact_primary_email_from_contact_emails on public.contact_emails;
create trigger trg_sync_contact_primary_email_from_contact_emails
after insert or update or delete on public.contact_emails
for each row execute function public.sync_contact_primary_email_from_contact_emails();

create or replace function public.sync_contact_email_to_contact_emails()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_email text;
begin
  if pg_trigger_depth() > 1 then return new; end if;
  v_email := public.normalize_contact_email(new.email);
  if tg_op = 'INSERT' or public.normalize_contact_email(old.email) is distinct from v_email then
    if v_email <> '' then
      insert into public.contact_emails(contact_id,email,is_primary,source,active)
      values(new.id,v_email,true,'contacts_schools.email',true)
      on conflict (contact_id, lower(btrim(email)))
      do update set is_primary=true,active=true,updated_at=now();
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_contact_email_to_contact_emails on public.contacts_schools;
create trigger trg_sync_contact_email_to_contact_emails
after insert or update of email on public.contacts_schools
for each row execute function public.sync_contact_email_to_contact_emails();

insert into public.contact_emails(contact_id,email,is_primary,source,active)
select cs.id,public.normalize_contact_email(cs.email),true,'backfill contacts_schools.email',true
from public.contacts_schools cs
where public.normalize_contact_email(cs.email) <> ''
on conflict (contact_id, lower(btrim(email)))
do update set is_primary=true,active=true,updated_at=now();

create or replace view public.contacts_unified_view as
select
  case
    when lower(coalesce(cs.client_type,''))='school'
      or (nullif(btrim(coalesce(cs.school,'')),'') is not null and lower(coalesce(cs.client_type,''))<>'authority') then 'school'
    when lower(coalesce(cs.client_type,''))='authority' then 'authority'
    else 'other'
  end as contact_domain,
  cs.client_type,cs.client_name,cs.authority_id,cs.school_id,cs.semel_mosad,
  coalesce(a.authority_name,cs.authority) as authority_name,
  cs.authority,coalesce(s.school_name,cs.school) as school_name,cs.school,
  cs.contact_name,cs.contact_role,cs.phone,cs.mobile,cs.email,cs.address,cs.notes,
  a.authority_code,coalesce(s.district,a.district) as district,s.city,
  'contacts_schools'::text as source_table,cs.id::text as source_id,
  coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',ce.id,'email',ce.email,'is_primary',ce.is_primary,'source',ce.source
    ) order by ce.is_primary desc,ce.id)
    from public.contact_emails ce
    where ce.contact_id=cs.id and ce.active
  ),'[]'::jsonb) as emails
from public.contacts_schools cs
left join public.authorities a on a.id=cs.authority_id
left join public.schools s on s.id=cs.school_id
where coalesce(lower(btrim(cs.active)),'yes') <> all(array['no','0','false'])
union all
select
  'school'::text,'school'::text,sch.school_name,sch.authority_id,sch.id,sch.semel_mosad,
  coalesce(a.authority_name,sch.authority),sch.authority,sch.school_name,sch.school_name,
  nullif(btrim(coalesce(sch.principal_name,'')),''),
  case when nullif(btrim(coalesce(sch.principal_name,'')),'') is not null then 'מנהל/ת בית ספר' else null end,
  nullif(btrim(coalesce(sch.school_phone,'')),''),null::text,null::text,
  nullif(btrim(coalesce(sch.institution_address,'')),''),null::text,
  a.authority_code,coalesce(sch.district,a.district),sch.city,
  'schools'::text,sch.id::text,'[]'::jsonb
from public.schools sch
left join public.authorities a on a.id=sch.authority_id
where coalesce(lower(btrim(sch.active)),'yes') <> all(array['no','0','false'])
  and nullif(btrim(coalesce(sch.school_name,'')),'') is not null
  and (
    nullif(btrim(coalesce(sch.principal_name,'')),'') is not null
    or nullif(btrim(coalesce(sch.school_phone,'')),'') is not null
    or nullif(btrim(coalesce(sch.institution_address,'')),'') is not null
  );

create or replace function public.trg_sync_dynamic_dropdown_lists()
returns trigger language plpgsql security definer
set search_path = public
as $$
begin
  if current_setting('app.skip_dynamic_lists_sync', true) = 'on' then return null; end if;
  perform public.sync_dynamic_dropdown_lists();
  return null;
end;
$$;
