-- Fix: public.lists.list_id has no usable auto-increment for trigger inserts.
--
-- Two possible states, both resulting in INSERT failures from sync_dynamic_dropdown_lists():
--   A) Plain bigint NOT NULL with no DEFAULT/sequence → "null value in column list_id"
--   B) GENERATED ALWAYS AS IDENTITY with stale/explicit-NULL insert → trigger fails
--
-- This migration handles both cases:
--   A → creates a sequence and sets it as the column DEFAULT
--   B → changes GENERATED ALWAYS to GENERATED BY DEFAULT, restarts sequence at MAX+1

DO $$
DECLARE
  v_next      bigint;
  v_is_id     text;
  v_id_gen    text;
BEGIN
  SELECT COALESCE(MAX(list_id), 0) + 1
  INTO v_next
  FROM public.lists;

  SELECT is_identity, identity_generation
  INTO v_is_id, v_id_gen
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name   = 'lists'
    AND column_name  = 'list_id';

  IF v_is_id = 'YES' THEN
    -- Case B: identity column
    IF v_id_gen = 'ALWAYS' THEN
      ALTER TABLE public.lists
        ALTER COLUMN list_id SET GENERATED BY DEFAULT;
    END IF;
    EXECUTE format(
      'ALTER TABLE public.lists ALTER COLUMN list_id RESTART WITH %s',
      v_next
    );
    RAISE NOTICE 'list_id identity sequence restarted at %', v_next;
  ELSE
    -- Case A: plain bigint, add a sequence + DEFAULT
    IF NOT EXISTS (
      SELECT 1
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = 'lists_list_id_seq'
    ) THEN
      CREATE SEQUENCE public.lists_list_id_seq;
    END IF;

    PERFORM setval('public.lists_list_id_seq', v_next, false);

    ALTER TABLE public.lists
      ALTER COLUMN list_id
        SET DEFAULT nextval('public.lists_list_id_seq'::regclass);

    ALTER SEQUENCE public.lists_list_id_seq
      OWNED BY public.lists.list_id;

    RAISE NOTICE 'lists_list_id_seq created and DEFAULT set, starts at %', v_next;
  END IF;
END $$;

-- Verify after running:
-- SELECT column_name, is_identity, identity_generation, column_default
-- FROM information_schema.columns
-- WHERE table_schema='public' AND table_name='lists' AND column_name='list_id';
--
-- Expected:
--   Case A → column_default = nextval('lists_list_id_seq'::regclass)
--   Case B → is_identity='YES', identity_generation='BY DEFAULT'
