-- Impact feedback default content: metrics, the 8 catalog programs, question bank and
-- v1 templates (generated by the template engine, not hand-built per form).
-- Idempotent: existing rows are never overwritten, existing templates keep their versions.
--
-- Course-specific questions are derived from the catalog syllabi
-- (frontend/public/catalog/catalog_programs_tashpaz.json, catalog_program_ids below):
-- topics, skills and the closing products (models, posters, pitch, venture) of each program.

insert into public.feedback_metrics (key, label, kind, sort_order, description) values
  ('knowledge',      'ידע והבנה',          'impact',  10, 'הבנת התחום, המושגים והשימושים שלו'),
  ('self_efficacy',  'מסוגלות וביטחון',     'impact',  20, 'אמונה ביכולת לפתח, לחקור, להוביל ולהתנסות'),
  ('interest',       'עניין וסקרנות',       'impact',  30, 'עניין בתחום, סקרנות ומעורבות'),
  ('skills',         'מיומנויות',          'impact',  40, 'עבודת צוות, חקר, תכנון, הצגה ומיומנויות ייחודיות לתוכנית'),
  ('attitudes',      'עמדות ותפיסות',       'impact',  50, 'תפיסות לגבי מדע, טכנולוגיה, אחריות ואתיקה'),
  ('continuation',   'כוונה להמשך',         'impact',  60, 'רצון להמשיך ללמוד, להתנסות או להפעיל שוב'),
  ('satisfaction',   'חוויה ושביעות רצון',  'impact',  70, 'הנאה, השתתפות והמלצה'),
  ('overall_impact', 'השפעה כוללת',         'impact',  80, 'השפעה כוללת, השגת מטרות ושינוי שנצפה'),
  ('content',        'איכות התוכן',         'program', 110, 'איכות, בהירות, רצף, התאמה לגיל, עומס וזמן'),
  ('delivery',       'העברה בכיתה והדרכה',  'program', 120, 'ישימות הפעילויות, מקצועיות וניהול הקבוצה'),
  ('operations',     'תפעול, ציוד ותמיכה',  'program', 130, 'חומרי הדרכה, ערכות, הכשרה ותמיכה מתעשיידע')
on conflict (key) do nothing;

-- Program mapping audited against the catalog pages (frontend/public/catalog/appendices/<gefen>.pdf):
--   ביומימיקרי 6089 (ד׳–ו׳) + 53828 (ז׳–י׳) · מנהיגות ירוקה 67867 (ד׳–ו׳) · טכנולוגיות החלל 57651 (ד׳–ו׳)
--   יישומי הבינה המלאכותית 53819 (ז׳–י׳) · סודות ויסודות הבינה המלאכותית 9545 (ז׳–ח׳)
--   רוקחים עולם 46091 (ז׳–י׳) · אופק – יזמות פרימיום 960 (ז׳–י׳) · פורצות דרך 67861 (ז׳–י׳)
-- "אופק לתעשייה" (52279, career/industry exposure) is a different catalog program and is NOT matched
-- automatically; an admin can still map such an activity manually.
-- default_age_band is used only when the activity has no parsable grade.
insert into public.feedback_programs (key, title, topic, catalog_program_ids, gefen_numbers, activity_name_patterns, exclude_patterns, default_age_band, sort_order) values
  ('biomimicry', 'ביומימיקרי – המצאות בהשראה מן הטבע', 'ביומימיקרי – המצאות בהשראת הטבע',
    array['program-01', 'program-11'], array['6089', '53828'], array['%ביומימיקרי%', '%ביומימקרי%'], array['%חדר בריחה%', '%הקסום%'], 'd_f', 10),
  ('green_leadership', 'מנהיגות ירוקה', 'קיימות ומנהיגות סביבתית',
    array['program-04'], array['67867'], array['%מנהיגות ירוקה%'], array[]::text[], 'd_f', 20),
  ('space_tech', 'טכנולוגיות החלל', 'טכנולוגיות החלל',
    array['program-03'], array['57651'], array['%טכנולוגיות החלל%', '%טכנולוגיות חלל%'], array[]::text[], 'd_f', 30),
  ('ai_applications', 'יישומי הבינה המלאכותית', 'יישומי בינה מלאכותית',
    array['program-10'], array['53819'], array['%יישומי AI%', '%AI יישומי%', '%יישומי הבינה%', '%יישומי בינה%'], array[]::text[], 'g_i', 40),
  ('pharma', 'רוקחים עולם', 'פיתוח תרופות ועולם הפרמצבטיקה',
    array['program-06'], array['46091'], array['%רוקחים עולם%', '%רוקחים%'], array[]::text[], 'g_i', 50),
  ('ofek', 'אופק – יזמות פרימיום לתעשייה', 'יזמות ותעשייה',
    array['program-07'], array['960'], array['%אופק%פרימיום%', '%יזמות פרימיום%', '%אופק יזמות%'], array[]::text[], 'g_i', 60),
  ('ai_foundations', 'סודות ויסודות הבינה המלאכותית', 'בינה מלאכותית',
    array['program-09'], array['9545'], array['%סודות ויסודות%', '%סודות%יסודות%'], array[]::text[], 'g_i', 70),
  ('trailblazers', 'פורצות דרך', 'יזמות וטכנולוגיה',
    array['program-05'], array['67861'], array['%פורצות דרך%'], array[]::text[], 'g_i', 80)
on conflict (key) do nothing;

-- Question bank. Fields: key, program (null = core), metric, type, audiences, stages,
-- comparison (same concept asked in PRE and POST), sort, required, wording (age variants:
-- a_c = א׳–ג׳, d_f = ד׳–ו׳, g_i = ז׳–ט׳, j_l = י׳–י״ב, default = fallback), options, scoring.
insert into public.feedback_questions (
  question_key, program_key, metric_key, question_type, audiences, stages, is_comparison,
  sort_order, default_required, wording, options, scoring
)
select q.key, q.program, q.metric, q.type, q.audiences, q.stages, coalesce(q.comparison, false),
  q.sort, coalesce(q.required, true), q.wording, coalesce(q.options, '[]'::jsonb),
  coalesce(q.scoring, case when q.type = 'rating_1_5' then '{"include_in_score": true}'::jsonb else '{"include_in_score": false}'::jsonb end)
from jsonb_to_recordset($json$[
  {"key":"s_core_knowledge","metric":"knowledge","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":10,
   "wording":{"default":"אני מבין/ה מה לומדים בתחום {topic} ואיך משתמשים בו בעולם האמיתי","a_c":"אני יודע/ת מה זה {topic}","j_l":"אני מבין/ה את העקרונות של התחום {topic} ואת השימושים שלו בעולם האמיתי"}},
  {"key":"s_core_efficacy","metric":"self_efficacy","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":20,
   "wording":{"default":"אני מאמין/ה שאני מסוגל/ת לפתח רעיון לפתרון של בעיה אמיתית","a_c":"אני יכול/ה להמציא פתרון לבעיה"}},
  {"key":"s_core_interest","metric":"interest","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":30,
   "wording":{"default":"התחום של {topic} מעניין אותי","a_c":"{topic} – זה מעניין אותי"}},
  {"key":"s_core_curiosity","metric":"interest","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":40,
   "wording":{"default":"אני אוהב/ת לשאול שאלות ולחקור איך דברים עובדים","a_c":"אני אוהב/ת לגלות איך דברים עובדים"}},
  {"key":"s_core_teamwork","metric":"skills","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":50,
   "wording":{"default":"אני יודע/ת לעבוד בצוות כדי לפתח רעיון משותף","a_c":"אני יודע/ת לעבוד יחד עם חברים על משימה"}},
  {"key":"s_core_attitude","metric":"attitudes","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":60,
   "wording":{"default":"אני חושב/ת שמדע וטכנולוגיה יכולים לעזור לפתור בעיות אמיתיות בעולם","a_c":"מדע וטכנולוגיה עוזרים לאנשים"}},
  {"key":"s_core_continuation","metric":"continuation","type":"rating_1_5","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":70,
   "wording":{"default":"הייתי רוצה להמשיך ללמוד ולהתנסות בתחום {topic} גם בעתיד","a_c":"הייתי רוצה ללמוד עוד על {topic}"}},

  {"key":"s_post_enjoy","metric":"satisfaction","type":"rating_1_5","audiences":["student"],"stages":["post"],"sort":210,
   "wording":{"default":"הפעילויות בתוכנית היו מעניינות","a_c":"נהניתי בפעילויות"}},
  {"key":"s_post_participation","metric":"satisfaction","type":"rating_1_5","audiences":["student"],"stages":["post"],"sort":220,
   "wording":{"default":"השתתפתי באופן פעיל במפגשים","a_c":"השתתפתי בפעילויות"}},
  {"key":"s_post_learning","metric":"knowledge","type":"rating_1_5","audiences":["student"],"stages":["post"],"sort":230,
   "wording":{"default":"הרגשתי שלמדתי בתוכנית דברים חדשים וחשובים","a_c":"למדתי דברים חדשים"}},
  {"key":"s_post_confidence","metric":"self_efficacy","type":"rating_1_5","audiences":["student"],"stages":["post"],"sort":240,
   "wording":{"default":"אחרי התוכנית אני מרגיש/ה בטוח/ה יותר להתנסות – לבנות, לחקור ולהמציא בעצמי","a_c":"עכשיו אני מרגיש/ה שאני יכול/ה לבנות ולהמציא בעצמי"}},
  {"key":"s_post_recommend","metric":"satisfaction","type":"rating_1_5","audiences":["student"],"stages":["post"],"sort":250,
   "wording":{"default":"הייתי ממליץ/ה לחברים להשתתף בתוכנית","a_c":"הייתי רוצה שגם חברים שלי ישתתפו"}},
  {"key":"s_post_overall","metric":"overall_impact","type":"rating_1_5","audiences":["student"],"stages":["post"],"sort":260,
   "wording":{"default":"התוכנית השפיעה עליי ושינתה את הדרך שבה אני חושב/ת על התחום","a_c":"התוכנית לימדה אותי משהו שאזכור"}},
  {"key":"s_post_open_like","metric":"satisfaction","type":"free_text","audiences":["student"],"stages":["post"],"sort":910,"required":false,
   "wording":{"default":"מה הכי אהבת בתוכנית?"}},
  {"key":"s_post_open_change","metric":"satisfaction","type":"free_text","audiences":["student"],"stages":["post"],"sort":920,"required":false,
   "wording":{"default":"מה היית משנה או משפר/ת בתוכנית?"}},

  {"key":"st_age_fit","metric":"content","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":10,
   "wording":{"default":"התוכנית הותאמה לגיל ולרמת התלמידים"}},
  {"key":"st_content_quality","metric":"content","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":20,
   "wording":{"default":"התוכן המקצועי של התוכנית איכותי ורלוונטי"}},
  {"key":"st_engagement","metric":"interest","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":30,
   "wording":{"default":"התלמידים גילו מעורבות והשתתפות פעילה במפגשים"}},
  {"key":"st_knowledge","metric":"knowledge","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":40,
   "wording":{"default":"התלמידים רכשו ידע חדש ומשמעותי בתחום {topic}"}},
  {"key":"st_efficacy","metric":"self_efficacy","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":50,
   "wording":{"default":"ניכר שהתלמידים מרגישים מסוגלים יותר לפתח רעיונות ופתרונות"}},
  {"key":"st_curiosity","metric":"interest","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":60,
   "wording":{"default":"התוכנית עוררה אצל התלמידים סקרנות ורצון לחקור"}},
  {"key":"st_creative","metric":"skills","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":70,
   "wording":{"default":"התוכנית פיתחה אצל התלמידים חשיבה יצירתית"}},
  {"key":"st_problem_solving","metric":"skills","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":80,
   "wording":{"default":"התוכנית פיתחה אצל התלמידים יכולת פתרון בעיות"}},
  {"key":"st_teamwork","metric":"skills","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":90,
   "wording":{"default":"התוכנית חיזקה את העבודה בצוות בין התלמידים"}},
  {"key":"st_change","metric":"overall_impact","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":100,
   "wording":{"default":"הבחנו בשינוי חיובי אצל התלמידים לאורך התוכנית"}},
  {"key":"st_instructor_prof","metric":"delivery","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":110,
   "wording":{"default":"המדריך/ה הפגין/ה מקצועיות וידע"}},
  {"key":"st_group_mgmt","metric":"delivery","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":120,
   "wording":{"default":"המדריך/ה ניהל/ה את הקבוצה היטב"}},
  {"key":"st_rapport","metric":"delivery","type":"rating_1_5","audiences":["educational_staff"],"stages":["final"],"sort":130,
   "wording":{"default":"המדריך/ה יצר/ה קשר טוב עם התלמידים"}},
  {"key":"st_again","metric":"continuation","type":"yes_no","audiences":["educational_staff"],"stages":["final"],"sort":140,
   "wording":{"default":"הייתם רוצים להפעיל את התוכנית שוב?"},
   "scoring":{"include_in_score":true,"yes":5,"no":1}},
  {"key":"st_change_areas","metric":"overall_impact","type":"multi_select","audiences":["educational_staff"],"stages":["final"],"sort":800,"required":false,
   "wording":{"default":"באילו תחומים הבחנתם בשינוי אצל התלמידים?"},
   "options":[{"value":"knowledge","label":"ידע והבנה"},{"value":"self_efficacy","label":"מסוגלות וביטחון"},{"value":"interest","label":"עניין וסקרנות"},{"value":"skills","label":"מיומנויות (חשיבה יצירתית, פתרון בעיות, עבודת צוות)"},{"value":"attitudes","label":"עמדות ותפיסות"},{"value":"continuation","label":"רצון להמשיך בתחום"},{"value":"none","label":"לא הבחנו בשינוי משמעותי"}]},
  {"key":"st_open_comments","metric":"satisfaction","type":"free_text","audiences":["educational_staff"],"stages":["final"],"sort":900,"required":false,
   "wording":{"default":"הערות, הצעות או דברים נוספים שחשוב לכם לשתף"}},

  {"key":"in_content_quality","metric":"content","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":10,
   "wording":{"default":"התוכן המקצועי של התוכנית איכותי"}},
  {"key":"in_clarity","metric":"content","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":20,
   "wording":{"default":"התוכן ברור ומובנה"}},
  {"key":"in_sequence","metric":"content","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":30,
   "wording":{"default":"רצף המפגשים הגיוני ובונה למידה מדורגת"}},
  {"key":"in_age_fit","metric":"content","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":40,
   "wording":{"default":"התוכן מותאם לגיל התלמידים"}},
  {"key":"in_load","metric":"content","type":"single_select","audiences":["instructor"],"stages":["final"],"sort":50,
   "wording":{"default":"איך היית מתאר/ת את רמת העומס של התוכן?"},
   "options":[{"value":"too_light","label":"דל מדי"},{"value":"balanced","label":"מאוזן"},{"value":"too_heavy","label":"עמוס מדי"}]},
  {"key":"in_time_fit","metric":"content","type":"single_select","audiences":["instructor"],"stages":["final"],"sort":60,
   "wording":{"default":"האם הזמן שהוקצה למפגשים התאים לתוכן?"},
   "options":[{"value":"not_enough","label":"הזמן לא הספיק"},{"value":"fits","label":"הזמן התאים"},{"value":"too_much","label":"נשאר זמן מיותר"}]},
  {"key":"in_ease","metric":"delivery","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":70,
   "wording":{"default":"קל להעביר את התוכן בכיתה"}},
  {"key":"in_activities_worked","metric":"delivery","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":80,
   "wording":{"default":"הפעילויות עבדו בפועל בכיתה כפי שתוכננו"}},
  {"key":"in_materials","metric":"operations","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":90,
   "wording":{"default":"חומרי ההדרכה (מערכים, מצגות) מספקים ונוחים לעבודה"}},
  {"key":"in_kits","metric":"operations","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":100,
   "wording":{"default":"הערכות והציוד היו מתאימים, תקינים וזמינים"}},
  {"key":"in_engagement","metric":"interest","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":110,
   "wording":{"default":"התלמידים היו מעורבים ומשתתפים לאורך הקורס"}},
  {"key":"in_goals","metric":"overall_impact","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":120,
   "wording":{"default":"מטרות הקורס הושגו"}},
  {"key":"in_support","metric":"operations","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":130,
   "wording":{"default":"התפעול והתמיכה מצד תעשיידע היו טובים"}},
  {"key":"in_training","metric":"operations","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":140,
   "wording":{"default":"ההכשרה שקיבלתי לקראת התוכנית הכינה אותי היטב"}},
  {"key":"in_again","metric":"continuation","type":"rating_1_5","audiences":["instructor"],"stages":["final"],"sort":150,
   "wording":{"default":"הייתי רוצה להדריך את התוכנית שוב"}},
  {"key":"in_open_best","metric":"content","type":"free_text","audiences":["instructor"],"stages":["final"],"sort":910,"required":false,
   "wording":{"default":"איזה חלק בתוכנית עבד הכי טוב?"}},
  {"key":"in_open_change","metric":"content","type":"free_text","audiences":["instructor"],"stages":["final"],"sort":920,"required":false,
   "wording":{"default":"איזה חלק בתוכן היית משנה?"}},
  {"key":"in_open_missing","metric":"content","type":"free_text","audiences":["instructor"],"stages":["final"],"sort":930,"required":false,
   "wording":{"default":"מה חסר בתוכנית?"}},
  {"key":"in_open_differently","metric":"delivery","type":"free_text","audiences":["instructor"],"stages":["final"],"sort":940,"required":false,
   "wording":{"default":"אם היית מעביר/ה את התוכנית שוב, מה היית עושה אחרת?"}}
]$json$::jsonb) as q(
  key text, program text, metric text, type text, audiences text[], stages text[], comparison boolean,
  sort int, required boolean, wording jsonb, options jsonb, scoring jsonb
)
on conflict (question_key) do nothing;

-- Course-specific questions, audited against each catalog page (summary, goals, skills, closing products).
-- Student questionnaires stay short: per program 2–3 comparison questions (asked in PRE and POST)
-- + 1–2 POST-only questions, i.e. at most 5 course questions in any student questionnaire.
-- The catalog source of each question is noted in "src".
insert into public.feedback_questions (
  question_key, program_key, metric_key, question_type, audiences, stages, is_comparison,
  sort_order, default_required, wording, options, scoring
)
select q.key, q.program, q.metric, 'rating_1_5', q.audiences, q.stages, coalesce(q.comparison, false),
  q.sort, true, q.wording, '[]'::jsonb, '{"include_in_score": true}'::jsonb
from jsonb_to_recordset($json$[
  {"key":"biomimicry_example","program":"biomimicry","metric":"knowledge","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"6089/53828: היכרות עם דוגמאות ביומימטיות והמצאות בהשראת הטבע",
   "wording":{"default":"אני יכול/ה לתת דוגמה להמצאה או לפתרון טכנולוגי שנוצרו בהשראת הטבע"}},
  {"key":"biomimicry_research","program":"biomimicry","metric":"skills","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"6089: חקר אורגניזם, רעיון מתוך הבנת מנגנון טבעי · 53828: ניתוח מנגנונים, הפשטת העיקרון הביולוגי",
   "wording":{"default":"אני יודע/ת לחקור מנגנון בטבע ולהסביר איך אפשר להיעזר בו כדי לפתור בעיה"}},
  {"key":"biomimicry_sustainability","program":"biomimicry","metric":"attitudes","audiences":["student"],"stages":["post"],"sort":300,
   "src":"6089: פתרונות אחראיים, שימושי ובר-קיימא · 53828: חדשנות מקיימת, עקרונות תכנון מקיימים",
   "wording":{"default":"למדתי שהטבע יכול לעזור לנו לפתח פתרונות ששומרים גם על הסביבה"}},
  {"key":"biomimicry_product","program":"biomimicry","metric":"overall_impact","audiences":["student"],"stages":["post"],"sort":310,
   "src":"תוצרי סיום: דגם ראשוני / דגם ביומימטי, פוסטר חקר / פוסטר מדעי",
   "wording":{"default":"אני גאה בדגם או בפוסטר שפיתחנו בהשראת הטבע"}},
  {"key":"biomimicry_staff","program":"biomimicry","metric":"knowledge","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"מטרה: חיבור בין מבנים ומנגנונים טבעיים לבין תכנון טכנולוגי",
   "wording":{"default":"התלמידים הצליחו לקשר בין מנגנונים בטבע לבין פתרונות טכנולוגיים"}},
  {"key":"biomimicry_instructor","program":"biomimicry","metric":"overall_impact","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"תוצרי סיום: דגם / אב-טיפוס ביומימטי ופוסטר",
   "wording":{"default":"התלמידים הגיעו לדגם או לפוסטר ביומימטי ברמה טובה"}},

  {"key":"green_responsibility","program":"green_leadership","metric":"attitudes","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"67867: אחריות סביבתית, חיבור לחיים בבית הספר ובקהילה הקרובה",
   "wording":{"default":"אני מרגיש/ה אחריות לשמור על הסביבה בבית הספר ובקהילה שלי"}},
  {"key":"green_leading","program":"green_leadership","metric":"self_efficacy","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"67867: לטפח מנהיגות סביבתית צעירה, יכולת להוביל שינוי קטן אך משמעותי",
   "wording":{"default":"אני מרגיש/ה שאני יכול/ה להוביל יוזמה סביבתית ולהשפיע בבית הספר או בקהילה"}},
  {"key":"green_challenge_solution","program":"green_leadership","metric":"skills","audiences":["student"],"stages":["post"],"sort":300,
   "src":"67867: חקר אתגר סביבתי מחיי היומיום, הדרך מהאתגר לפתרון, פתרון יישומי וברור",
   "wording":{"default":"למדתי לקחת אתגר סביבתי מהסביבה שלי ולפתח עבורו פתרון מעשי"}},
  {"key":"green_digital_tools","program":"green_leadership","metric":"skills","audiences":["student"],"stages":["post"],"sort":310,
   "src":"67867: טכנולוגיה וכלים דיגיטליים לתכנון, המחשה או הצגה של הרעיון · תוצרים: תוצר חזותי, דגם ראשוני",
   "wording":{"default":"השתמשנו בכלים דיגיטליים או טכנולוגיים כדי לתכנן או להמחיש את הפתרון הסביבתי שלנו"}},
  {"key":"green_staff","program":"green_leadership","metric":"attitudes","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"67867: אחריות אישית וקבוצתית, יוזמה סביבתית",
   "wording":{"default":"התלמידים גילו יוזמה ואחריות סביבתית במהלך התוכנית"}},
  {"key":"green_instructor","program":"green_leadership","metric":"skills","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"67867: מעבר מאתגר לפתרון יישומי · תוצרים: מיזם סביבתי, פיץ׳",
   "wording":{"default":"הקבוצות הצליחו לעבור מאתגר סביבתי מוגדר לפתרון יישומי ולהציג אותו"}},

  {"key":"space_spinoff","program":"space_tech","metric":"knowledge","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"57651: עקרון הספין-אוף והעברה טכנולוגית, פתרונות שימושיים בחיי היומיום",
   "wording":{"default":"אני יכול/ה לתת דוגמה לטכנולוגיה שפותחה עבור החלל ומשמשת אותנו בחיי היומיום"}},
  {"key":"space_engineering","program":"space_tech","metric":"skills","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"57651: חשיבה הנדסית, מעבר מרעיון לכיוון פעולה, אב-טיפוס",
   "wording":{"default":"אני יודע/ת לקחת רעיון ולתכנן ממנו דגם, כמו מהנדס/ת"}},
  {"key":"space_conditions","program":"space_tech","metric":"knowledge","audiences":["student"],"stages":["post"],"sort":300,
   "src":"57651: תנאי חיים בסביבה קיצונית מחוץ לאטמוספרה והצורך בפתרונות ייחודיים",
   "wording":{"default":"למדתי איך תנאי החלל משפיעים על האדם ועל הטכנולוגיה"}},
  {"key":"space_pitch","program":"space_tech","metric":"skills","audiences":["student"],"stages":["post"],"sort":310,
   "src":"תוצרי סיום: פיץ׳ יזמי, פרזנטציה",
   "wording":{"default":"הצלחנו להציג את הרעיון של הקבוצה שלנו בפיץ׳ מול קהל"}},
  {"key":"space_staff","program":"space_tech","metric":"knowledge","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"57651: כיצד צורך שנולד בחלל הופך לפתרון רלוונטי על פני כדור הארץ",
   "wording":{"default":"התלמידים הבינו את הקשר בין אתגרי החלל לבין פתרונות לחיים בכדור הארץ"}},
  {"key":"space_instructor","program":"space_tech","metric":"delivery","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"תוצרי סיום: מוצר טכנולוגי, אב-טיפוס, פיץ׳ יזמי",
   "wording":{"default":"שלבי בניית האב־טיפוס והפיץ׳ היו ישימים בכיתה"}},

  {"key":"aiapp_domains","program":"ai_applications","metric":"knowledge","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"53819: AI ברפואה, חקלאות, תעשייה, תחבורה, חינוך וסביבה",
   "wording":{"default":"אני יכול/ה להסביר איך בינה מלאכותית משמשת בתחומים כמו רפואה, חקלאות, תעשייה ותחבורה"}},
  {"key":"aiapp_critical","program":"ai_applications","metric":"attitudes","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"53819: חשיבה ביקורתית, ניתוח הזדמנויות, סיכונים ודילמות",
   "wording":{"default":"אני בוחן/ת באופן ביקורתי את היתרונות והסיכונים של שימוש בבינה מלאכותית"}},
  {"key":"aiapp_ethics","program":"ai_applications","metric":"attitudes","audiences":["student"],"stages":["post"],"sort":300,
   "src":"53819: שאלות של פרטיות, אחריות, אמון, תעסוקה, ביטחון והשפעה חברתית",
   "wording":{"default":"אני מבין/ה את השאלות האתיות והחברתיות שהבינה המלאכותית מעוררת (למשל פרטיות, אמון ותעסוקה)"}},
  {"key":"aiapp_idea","program":"ai_applications","metric":"skills","audiences":["student"],"stages":["post"],"sort":310,
   "src":"53819 תוצרים: עבודת חקר, רעיון יישומי, אב-טיפוס רעיוני, פיץ׳",
   "wording":{"default":"פיתחתי רעיון יישומי לשימוש בבינה מלאכותית בתחום שבחרתי"}},
  {"key":"aiapp_staff","program":"ai_applications","metric":"attitudes","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"53819: הבנה ביקורתית וערכית, שימוש אחראי בטכנולוגיה",
   "wording":{"default":"התלמידים מגלים חשיבה ביקורתית ואחריות בנוגע לשימוש בבינה מלאכותית"}},
  {"key":"aiapp_instructor","program":"ai_applications","metric":"content","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"53819: מקרי בוחן מהמציאות בתחומי היישום, דיון ערכי",
   "wording":{"default":"מקרי הבוחן מתחומי היישום (רפואה, חקלאות, תעשייה, תחבורה, חינוך) עוררו דיון משמעותי"}},

  {"key":"pharma_drug_in_body","program":"pharma","metric":"knowledge","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"46091: דרכי מתן תרופה, ספיגה, השפעה בגוף ומסלול התרופה עד אתר המטרה",
   "wording":{"default":"אני מבין/ה איך תרופה פועלת בגוף – איך היא ניתנת, נספגת ומגיעה למקום שבו היא צריכה לפעול"}},
  {"key":"pharma_patient_need","program":"pharma","metric":"skills","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"46091: בחירת מחלה או צורך רפואי, בניית פרסונה להבנת חוויית המטופל",
   "wording":{"default":"אני יודע/ת לזהות צורך רפואי ולהבין את חוויית המטופל כבסיס לפיתוח פתרון"}},
  {"key":"pharma_venture","program":"pharma","metric":"self_efficacy","audiences":["student"],"stages":["post"],"sort":300,
   "src":"46091: גיבוש רעיון חדשני ופיתוח מיזם רפואי עם משוב ממומחים",
   "wording":{"default":"הצלחנו לפתח מיזם שעונה על צורך רפואי אמיתי"}},
  {"key":"pharma_product","program":"pharma","metric":"overall_impact","audiences":["student"],"stages":["post"],"sort":310,
   "src":"תוצרי סיום: דגם מוצר, פוסטר מדעי, פוסטר שיווקי, מצגת מיזם, הצגת פיץ׳",
   "wording":{"default":"אני גאה בדגם, בפוסטרים ובמצגת שהכנו למיזם"}},
  {"key":"pharma_staff","program":"pharma","metric":"knowledge","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"46091: הבנה יישומית של עולם התרופות והפרמצבטיקה",
   "wording":{"default":"התלמידים נחשפו לעולם הפרמצבטיקה והבינו את תהליך פיתוח המוצר הרפואי"}},
  {"key":"pharma_instructor","program":"pharma","metric":"delivery","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"46091: משוב מחוקר או יועץ מקצועי, דיוק ההיבטים המדעיים והשיווקיים",
   "wording":{"default":"שלב פיתוח המיזם והמשוב מהמומחים התאימו לרמת התלמידים"}},

  {"key":"ofek_need","program":"ofek","metric":"skills","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"960: בוחנים אתגר אמיתי ומגדירים צורך",
   "wording":{"default":"אני יודע/ת לזהות צורך אמיתי ולהפוך אותו לאתגר שאפשר לפתח לו פתרון"}},
  {"key":"ofek_audience","program":"ofek","metric":"skills","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"960 מיומנויות: חקר שוק, הגדרת קהל יעד, איסוף משוב",
   "wording":{"default":"אני יודע/ת להגדיר קהל יעד ולבדוק בעזרת חקר שוק אם הרעיון מתאים לו"}},
  {"key":"ofek_decisions","program":"ofek","metric":"self_efficacy","audiences":["student"],"stages":["post"],"sort":300,
   "src":"960: קבלת החלטות, השוואת כיוונים, נקודות עצירה לבחירה ודיוק",
   "wording":{"default":"אני מרגיש/ה בטוח/ה יותר לקבל החלטות בצוות לגבי הכיוון של מיזם"}},
  {"key":"ofek_industry_feedback","program":"ofek","metric":"knowledge","audiences":["student"],"stages":["post"],"sort":310,
   "src":"960: ליווי חברה מאמצת, משוב מקצועי מהשטח, הבנה כיצד רעיון מתפתח בסביבה תעשייתית",
   "wording":{"default":"הליווי והמשוב מהחברה המאמצת עזרו לי להבין איך רעיון מתפתח בתעשייה"}},
  {"key":"ofek_staff","program":"ofek","metric":"skills","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"960: מצורך אמיתי לפתרון בעל ערך בתהליך מדורג",
   "wording":{"default":"התלמידים למדו לעבור מצורך לפתרון בתהליך יזמי מסודר"}},
  {"key":"ofek_instructor","program":"ofek","metric":"delivery","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"960: חברה מאמצת, משוב מקצועי, מסגרת המדמה אקסלרטור תעשייתי",
   "wording":{"default":"ליווי החברה המאמצת והמשוב המקצועי תרמו לתהליך של הקבוצה"}},

  {"key":"aifound_prompts","program":"ai_foundations","metric":"skills","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"9545: כוחו של הפרומפט – ניסוח נכון משפיע על התוצאה; שימוש מדויק ואחראי בכלי AI",
   "wording":{"default":"אני יודע/ת לכתוב לכלי בינה מלאכותית הוראה (פרומפט) ברורה שתעזור לי לקבל את מה שאני צריך/ה"}},
  {"key":"aifound_verify","program":"ai_foundations","metric":"attitudes","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"9545 מיומנויות: בדיקת מידע, חשיבה ביקורתית; דילמת אמינות",
   "wording":{"default":"אני בודק/ת אם מידע שקיבלתי מבינה מלאכותית נכון לפני שאני משתמש/ת בו"}},
  {"key":"aifound_ethics","program":"ai_foundations","metric":"attitudes","audiences":["student"],"stages":["post"],"sort":300,
   "src":"9545: דילמות פרטיות, אחריות, אמינות וקניין רוחני; אמנה לשימוש חכם ובטוח",
   "wording":{"default":"אני מכיר/ה כללים לשימוש אחראי ובטוח בבינה מלאכותית (למשל פרטיות וזכויות יוצרים)"}},
  {"key":"aifound_tools","program":"ai_foundations","metric":"skills","audiences":["student"],"stages":["post"],"sort":310,
   "src":"9545 תוצרים: פרויקט גמר, תוצר דיגיטלי, תיק כלים",
   "wording":{"default":"השתמשתי בכלי בינה מלאכותית כדי ליצור תוצר בפרויקט הגמר"}},
  {"key":"aifound_staff","program":"ai_foundations","metric":"attitudes","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"9545: שימוש מושכל בכלי AI, אחריות טכנולוגית",
   "wording":{"default":"התלמידים מפגינים שימוש אחראי וביקורתי בכלי בינה מלאכותית"}},
  {"key":"aifound_instructor","program":"ai_foundations","metric":"delivery","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"9545 סילבוס: למידת מכונה וראייה ממוחשבת, פרומפטיאדה, מכונה מוסרית",
   "wording":{"default":"הפעילויות המעשיות (למידת מכונה, ראייה ממוחשבת, פרומפטיאדה) עבדו היטב בכיתה"}},

  {"key":"trail_stem","program":"trailblazers","metric":"self_efficacy","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":100,
   "src":"67861: תחושת מסוגלות לפעול בעולמות הטכנולוגיה; גישת STEM",
   "wording":{"default":"אני מאמינה שאני יכולה להצליח בתחומי מדע, טכנולוגיה והנדסה"}},
  {"key":"trail_leadership","program":"trailblazers","metric":"self_efficacy","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":110,
   "src":"67861: זהות מובילה, מנהיגות נשית, יכולת להוביל שינוי",
   "wording":{"default":"אני רואה את עצמי כמי שיכולה להוביל, ליזום ולהשפיע"}},
  {"key":"trail_barriers","program":"trailblazers","metric":"attitudes","audiences":["student"],"stages":["pre","post"],"comparison":true,"sort":120,
   "src":"67861: התבוננות ביקורתית על חסמים, פריצת מחסומים",
   "wording":{"default":"חסמים לא יעצרו אותי מלבחור לפעול בתחום טכנולוגי"}},
  {"key":"trail_voice","program":"trailblazers","metric":"skills","audiences":["student"],"stages":["post"],"sort":300,
   "src":"67861: קול אישי, עמידה מול קהל · תוצרים: פיץ׳ ופרזנטציה",
   "wording":{"default":"אני מרגישה בנוח להשמיע את הקול שלי ולהציג את הרעיונות שלי מול קהל"}},
  {"key":"trail_staff","program":"trailblazers","metric":"self_efficacy","audiences":["educational_staff"],"stages":["final"],"sort":500,
   "src":"67861: מסוגלות ומנהיגות",
   "wording":{"default":"ניכרת אצל המשתתפות עלייה בביטחון העצמי ובמנהיגות"}},
  {"key":"trail_instructor","program":"trailblazers","metric":"overall_impact","audiences":["instructor"],"stages":["final"],"sort":500,
   "src":"67861: מפגש עם השראה נשית ותהליך תיכון הנדסי מלא לפיתוח מיזם",
   "wording":{"default":"המפגש עם השראה נשית מהתעשייה ועבודת המיזם תרמו להעצמת המשתתפות"}}
]$json$::jsonb) as q(
  key text, program text, metric text, audiences text[], stages text[], comparison boolean, sort int, wording jsonb
)
on conflict (question_key) do nothing;

-- Templates: program x (student pre, student post, educational staff, instructor).
insert into public.feedback_templates (program_key, audience, stage, title)
select p.key, s.audience, s.stage, p.title || ' – ' || s.label
from public.feedback_programs p
cross join (values
  ('student', 'pre', 'תלמידים – פתיחה'),
  ('student', 'post', 'תלמידים – סיום'),
  ('educational_staff', 'final', 'צוות חינוכי'),
  ('instructor', 'final', 'מדריך')
) as s(audience, stage, label)
on conflict (program_key, audience, stage) do nothing;

-- v1 for every template that has no version yet: compose (core + course) and publish.
do $$
declare
  t record;
  v_version uuid;
begin
  for t in
    select tp.* from public.feedback_templates tp
    where not exists (select 1 from public.feedback_template_versions v where v.template_id = tp.id)
  loop
    v_version := private.feedback_compose_draft(t.id);
    update public.feedback_template_versions
    set intro_text = case
      when t.audience = 'student' and t.stage = 'pre' then 'לפני שמתחילים – נשמח לדעת מה אתם חושבים ומרגישים. אין תשובות נכונות או לא נכונות, והשאלון אנונימי.'
      when t.audience = 'student' then 'סיימנו את התוכנית! נשמח לשמוע איך היה ומה השתנה אצלכם. השאלון אנונימי.'
      when t.audience = 'educational_staff' then 'נשמח לשמוע את הערכתכם לגבי התוכנית ולגבי מה שראיתם אצל התלמידים. המשוב עוזר לנו להשתפר.'
      else 'חשוב לנו לשמוע מה את/ה באמת חושב/ת על התוכן, על הקבוצה ועל התפעול. המשוב מגיע לצוות הניהול של תעשיידע בלבד.'
    end,
    notes = 'גרסת ברירת מחדל'
    where id = v_version;
    perform private.feedback_publish_version(v_version);
  end loop;
end $$;

notify pgrst, 'reload schema';
