create table if not exists public.school_calendar (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  title text not null,
  category text not null,
  start_date date,
  end_date date,
  resume_date date,
  applies_to text not null default '',
  day_status text not null default 'אירוע מידע',
  school_day_end_time time without time zone,
  hebrew_date text,
  notes text,
  date_status text not null default 'מופיע בחוזר',
  source_discrepancy boolean not null default false,
  discrepancy_note text,
  source_url text,
  show_on_main_calendar boolean not null default true,
  blocks_scheduling boolean not null default false,
  enforce_end_time boolean not null default false,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint school_calendar_date_range_check check (
    start_date is null or end_date is null or end_date >= start_date
  )
);

comment on table public.school_calendar is
  'Single source of truth for Ministry of Education calendar events shown in month/week views and used for activity date validation.';

create index if not exists school_calendar_active_dates_idx
  on public.school_calendar (start_date, end_date)
  where is_active = true;

alter table public.school_calendar enable row level security;

grant select on table public.school_calendar to authenticated;

drop policy if exists "Authenticated users can view school calendar" on public.school_calendar;
create policy "Authenticated users can view school calendar"
  on public.school_calendar
  for select
  to authenticated
  using (true);

create or replace function public.set_school_calendar_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists school_calendar_set_updated_at on public.school_calendar;
create trigger school_calendar_set_updated_at
before update on public.school_calendar
for each row execute function public.set_school_calendar_updated_at();

create or replace function public.enforce_school_calendar_on_activity()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  activity_date date;
  conflict_title text;
  shortened_title text;
  shortened_end_time time without time zone;
begin
  if coalesce(new.activity_season, '') like 'summer_%' then
    return new;
  end if;

  foreach activity_date in array array[
      NEW.start_date,
      NEW.date_1,
      NEW.date_2,
      NEW.date_3,
      NEW.date_4,
      NEW.date_5,
      NEW.date_6,
      NEW.date_7,
      NEW.date_8,
      NEW.date_9,
      NEW.date_10,
      NEW.date_11,
      NEW.date_12,
      NEW.date_13,
      NEW.date_14,
      NEW.date_15,
      NEW.date_16,
      NEW.date_17,
      NEW.date_18,
      NEW.date_19,
      NEW.date_20,
      NEW.date_21,
      NEW.date_22,
      NEW.date_23,
      NEW.date_24,
      NEW.date_25,
      NEW.date_26,
      NEW.date_27,
      NEW.date_28,
      NEW.date_29,
      NEW.date_30,
      NEW.date_31,
      NEW.date_32,
      NEW.date_33,
      NEW.date_34,
      NEW.date_35
  ]
  loop
    continue when activity_date is null;

    select sc.title
      into conflict_title
    from public.school_calendar sc
    where sc.is_active = true
      and sc.blocks_scheduling = true
      and sc.start_date is not null
      and activity_date between sc.start_date and coalesce(sc.end_date, sc.start_date)
    order by sc.start_date, sc.id
    limit 1;

    if conflict_title is not null then
      raise exception using
        errcode = '23514',
        message = 'activity_date_on_school_holiday',
        detail = activity_date::text || '|' || conflict_title;
    end if;

    conflict_title := null;

    if new.end_time is not null then
      select sc.title, sc.school_day_end_time
        into shortened_title, shortened_end_time
      from public.school_calendar sc
      where sc.is_active = true
        and sc.enforce_end_time = true
        and sc.school_day_end_time is not null
        and sc.start_date is not null
        and activity_date between sc.start_date and coalesce(sc.end_date, sc.start_date)
        and new.end_time > sc.school_day_end_time
      order by sc.start_date, sc.id
      limit 1;

      if shortened_title is not null then
        raise exception using
          errcode = '23514',
          message = 'activity_after_shortened_school_day',
          detail = activity_date::text || '|' || shortened_title || '|' || shortened_end_time::text;
      end if;

      shortened_title := null;
      shortened_end_time := null;
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists activities_enforce_school_calendar on public.activities;
create trigger activities_enforce_school_calendar
before insert or update of start_date, end_time, activity_season,
  date_1, date_2, date_3, date_4, date_5, date_6, date_7, date_8, date_9, date_10,
  date_11, date_12, date_13, date_14, date_15, date_16, date_17, date_18, date_19, date_20,
  date_21, date_22, date_23, date_24, date_25, date_26, date_27, date_28, date_29, date_30,
  date_31, date_32, date_33, date_34, date_35
on public.activities
for each row execute function public.enforce_school_calendar_on_activity();
