create table if not exists public.team_calendar_events (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  event_date date not null,
  title text not null,
  owner_name text,
  event_type text not null default 'task'
    check (event_type in ('task', 'vacation', 'event', 'training', 'milestone')),
  notes text not null default '',
  show_on_main_calendar boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.team_calendar_events is
  'Internal team tasks, vacations, milestones and events displayed on the shared month calendar. Kept separate from Ministry school holidays and employee birthdays.';

alter table public.team_calendar_events enable row level security;

drop policy if exists "Authenticated users can read team calendar events" on public.team_calendar_events;
create policy "Authenticated users can read team calendar events"
on public.team_calendar_events
for select
to authenticated
using (is_active = true and show_on_main_calendar = true);

insert into public.team_calendar_events
  (external_key, event_date, title, owner_name, event_type)
values
  ('TEAM-20260802-01', '2026-08-02', 'מיפוי קורסים', 'עדן', 'task'),
  ('TEAM-20260802-02', '2026-08-02', 'תזכורת למשוב קיץ לצוות החינוכי', 'עדן', 'task'),
  ('TEAM-20260802-03', '2026-08-02', 'מיפוי מדריכים', 'עידן', 'task'),
  ('TEAM-20260802-04', '2026-08-02', 'סגירת שנת תשפ״ו', null, 'milestone'),
  ('TEAM-20260803-01', '2026-08-03', 'חופשה - גיל', 'גיל', 'vacation'),
  ('TEAM-20260803-02', '2026-08-03', 'חופשה - עידן', 'עידן', 'vacation'),
  ('TEAM-20260804-01', '2026-08-04', 'סיכום משוב קיץ של הצוות החינוכי', 'עידן', 'task'),
  ('TEAM-20260805-01', '2026-08-05', 'איסוף ציוד קיץ וספירת מלאי', 'גיל', 'task'),
  ('TEAM-20260805-02', '2026-08-05', 'ספירת מלאי ציוד קיץ', 'הילה', 'task'),
  ('TEAM-20260805-03', '2026-08-05', 'הפצת אישורי גפ״ן', 'עדן', 'task'),
  ('TEAM-20260806-01', '2026-08-06', 'חופשה - גיל', 'גיל', 'vacation'),
  ('TEAM-20260806-02', '2026-08-06', 'חופשה - עידן', 'עידן', 'vacation'),
  ('TEAM-20260809-01', '2026-08-09', 'חופשה - גיל', 'גיל', 'vacation'),
  ('TEAM-20260809-02', '2026-08-09', 'חופשה - עידן', 'עידן', 'vacation'),
  ('TEAM-20260810-01', '2026-08-10', 'חופשה - גיל', 'גיל', 'vacation'),
  ('TEAM-20260810-02', '2026-08-10', 'חופשה - עידן', 'עידן', 'vacation'),
  ('TEAM-20260811-01', '2026-08-11', 'חופשה - עדן', 'עדן', 'vacation'),
  ('TEAM-20260812-01', '2026-08-12', 'חופשה - עדן', 'עדן', 'vacation'),
  ('TEAM-20260813-01', '2026-08-13', 'חופשה - גיל', 'גיל', 'vacation'),
  ('TEAM-20260813-02', '2026-08-13', 'חופשה - טוני', 'טוני', 'vacation'),
  ('TEAM-20260813-03', '2026-08-13', 'חופשה - עידן', 'עידן', 'vacation'),
  ('TEAM-20260816-01', '2026-08-16', 'חופשה - עדן', 'עדן', 'vacation'),
  ('TEAM-20260816-02', '2026-08-16', 'חופשה - טוני', 'טוני', 'vacation'),
  ('TEAM-20260817-01', '2026-08-17', 'חופשה - עדן', 'עדן', 'vacation'),
  ('TEAM-20260817-02', '2026-08-17', 'חופשה - טוני', 'טוני', 'vacation'),
  ('TEAM-20260818-01', '2026-08-18', 'חופשה - עדן', 'עדן', 'vacation'),
  ('TEAM-20260819-01', '2026-08-19', 'תחילת התיאומים', 'עדן', 'milestone'),
  ('TEAM-20260827-01', '2026-08-27', 'מנהלי פעילות שולחים גאנט לאישור', 'עידן', 'task'),
  ('TEAM-20260830-01', '2026-08-30', 'נהלי עבודה', 'עידן', 'task'),
  ('TEAM-20260830-02', '2026-08-30', 'תיק נהלים - עמותה', 'עידן', 'task'),
  ('TEAM-20260901-01', '2026-09-01', 'גיוס מדריכים', 'גיל', 'task'),
  ('TEAM-20260901-02', '2026-09-01', 'קטלוג תוכניות - למידה מלאה', 'גיל', 'task'),
  ('TEAM-20260901-03', '2026-09-01', 'קטלוג תוכניות - למידה מלאה', 'הילה', 'task'),
  ('TEAM-20260901-04', '2026-09-01', 'קטלוג תוכניות - היכרות וידע בסיסי', 'עדן', 'task'),
  ('TEAM-20260901-05', '2026-09-01', 'ביצוע שיבוצים', 'עדן', 'task'),
  ('TEAM-20260901-06', '2026-09-01', 'גיוס מדריכים', 'עידן', 'task'),
  ('TEAM-20260906-01', '2026-09-06', 'ספירת מלאי דפוס', 'גיל', 'task'),
  ('TEAM-20260906-02', '2026-09-06', 'בקרת מלאי אצל המדריכים - דפוס', 'עדן', 'task'),
  ('TEAM-20260906-03', '2026-09-06', 'הרמת כוסית - התאחדות התעשיינים', null, 'event'),
  ('TEAM-20260907-01', '2026-09-07', 'הצגת תוצרים במפעל אסם', null, 'event'),
  ('TEAM-20260907-02', '2026-09-07', 'מערכת הגפ״ן - חפיפה לכולם', 'עידן', 'training'),
  ('TEAM-20260915-01', '2026-09-15', 'הכשרת מדריכים', 'מנהלים', 'training'),
  ('TEAM-20260916-01', '2026-09-16', 'הכשרת מדריכים', 'מנהלים', 'training'),
  ('TEAM-20260917-01', '2026-09-17', 'הכשרת מדריכים', 'מנהלים', 'training')
on conflict (external_key) do update set
  event_date = excluded.event_date,
  title = excluded.title,
  owner_name = excluded.owner_name,
  event_type = excluded.event_type,
  show_on_main_calendar = true,
  is_active = true,
  updated_at = now();
